find_package(BSON REQUIRED)

find_path(DAYLITE_INCLUDE_DIR daylite/node.hpp PATHS "${CMAKE_SOURCE_PREFIX}")
find_library(DAYLITE_LIBRARY NAMES daylite libdaylite PATHS "${CMAKE_SOURCE_PREFIX}")

set(DAYLITE_LIBRARIES ${DAYLITE_LIBRARY} ${BSON_LIBRARIES})
set(DAYLITE_INCLUDE_DIRS ${DAYLITE_INCLUDE_DIR} ${BSON_INCLUDE_DIRS})

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(Daylite DEFAULT_MSG DAYLITE_LIBRARY DAYLITE_INCLUDE_DIR)

mark_as_advanced(DAYLITE_INCLUDE_DIR DAYLITE_LIBRARY)